# Generated by Django 4.2.1 on 2023-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SU_Staff',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='STAFF ID')),
                ('name', models.CharField(max_length=50, verbose_name='STAFF NAME')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'SU Staff',
                'verbose_name_plural': 'SU Staffs',
            },
        ),
    ]
