# Generated by Django 4.2.1 on 2023-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SU_Staff',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='STAFF ID')),
                ('name', models.CharField(max_length=256, verbose_name='STAFF NAME')),
                ('title', models.CharField(choices=[('', ''), ('Prof.', 'Prof.'), ('Assoc. Prof.', 'Assoc. Prof.'), ('Assoc. Prof. Dr', 'Assoc. Prof. Dr'), ('Prof. Datuk Dr', 'Prof. Datuk Dr'), ('Prof. Datin Dr', 'Prof. Datin Dr'), ('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms')], default='', max_length=20, verbose_name='TITLE')),
                ('status', models.BooleanField(default=True, verbose_name='STATUS')),
            ],
            options={
                'verbose_name': 'SU Staff',
                'verbose_name_plural': 'SU Staffs',
            },
        ),
    ]
