# Generated by Django 4.2.1 on 2023-06-17 12:57

from django.db import migrations, models
import django.db.models.deletion
import su_staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=20, primary_key=True,
                 serialize=False, verbose_name='DEPARTMENT ID')),
                ('dept_name', models.CharField(
                    max_length=255, verbose_name='DEPARTMENT NAME')),
                ('staff_id', models.ForeignKey(blank=True, db_column='staff_id', null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='su_staffs.su_staff')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=20,
                 primary_key=True, serialize=False, verbose_name='SCHOOL ID')),
                ('school_name', models.CharField(
                    max_length=255, verbose_name='SCHOOL NAME')),
                ('dept_id', models.ForeignKey(db_column='dept_id', default=su_staffs.models.get_default_dept,
                 on_delete=django.db.models.deletion.CASCADE, to='su_staffs.department')),
            ],
        ),
        migrations.AddField(
            model_name='su_staff',
            name='dept_id',
            field=models.ForeignKey(db_column='dept_id', default=su_staffs.models.get_default_dept,
                                    on_delete=django.db.models.deletion.CASCADE, to='su_staffs.department'),
        ),
        migrations.AddField(
            model_name='su_staff',
            name='school_id',
            field=models.ForeignKey(db_column='school_id', default=su_staffs.models.get_default_school,
                                    on_delete=django.db.models.deletion.CASCADE, to='su_staffs.school'),
        ),
    ]
