# Generated by Django 4.2.1 on 2023-06-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='SCHOOL ID'),
        ),
        migrations.AlterField(
            model_name='su_staff',
            name='school_id',
            field=models.ForeignKey(db_column='school_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='su_staffs.school'),
        ),
    ]
