# Generated by Django 4.2.1 on 2023-06-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0002_department_school_su_staff_dept_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='staff_id',
        ),
    ]
