# Generated by Django 4.2.1 on 2023-06-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0003_alter_school_school_id_alter_su_staff_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='DEPARTMENT ID')),
                ('dept_name', models.CharField(max_length=255, verbose_name='DEPARTMENT NAME')),
            ],
        ),
    ]
