# Generated by Django 4.2.1 on 2023-06-17 14:39

from django.db import migrations, models
import django.db.models.deletion
import su_staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0003_remove_department_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='dept_id',
        ),
        migrations.AddField(
            model_name='department',
            name='school_id',
            field=models.ForeignKey(db_column='school_id', default=su_staffs.models.get_default_school, on_delete=django.db.models.deletion.CASCADE, to='su_staffs.school'),
        ),
    ]
