# Generated by Django 4.2.1 on 2023-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0003_alter_su_staff_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='su_staff',
            name='title',
            field=models.CharField(choices=[('', ''), ('PROF', 'Prof.'), ('AP', 'Assoc. Prof.'), ('APD', 'Assoc. Prof. Dr.'), ('DR', 'Dr.'), ('MR', 'Mr'), ('MS', 'Ms')], default='', max_length=4),
        ),
    ]
