# Generated by Django 4.2.1 on 2023-06-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0004_remove_school_dept_id_department_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='su_staff',
            name='school_id',
        ),
    ]
