# Generated by Django 4.2.1 on 2023-06-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0004_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='school_id',
            field=models.ForeignKey(db_column='school_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='su_staffs.school'),
        ),
    ]
