# Generated by Django 4.2.1 on 2023-06-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0005_department_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='su_staff',
            name='dept_id',
            field=models.ForeignKey(db_column='dept_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='su_staffs.department'),
        ),
        migrations.AlterField(
            model_name='su_staff',
            name='status',
            field=models.BooleanField(default=True, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='su_staff',
            name='title',
            field=models.CharField(choices=[('', ''), ('Prof.', 'Prof.'), ('Assoc. Prof.', 'Assoc. Prof.'), ('Assoc. Prof. Dr', 'Assoc. Prof. Dr'), ('Prof. Datuk Dr', 'Prof. Datuk Dr'), ('Prof. Datin Dr', 'Prof. Datin Dr'), ('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms')], default='', max_length=20, verbose_name='TITLE'),
        ),
    ]
