# Generated by Django 4.2.1 on 2023-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0006_alter_su_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='su_staff',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='su_staff',
            name='title',
            field=models.CharField(choices=[('', ''), ('PROF', 'Prof.'), ('AP', 'Assoc. Prof.'), ('APD', 'Assoc. Prof. Dr.'), ('DR', 'Dr.'), ('MR', 'Mr'), ('MS', 'Ms')], default='', max_length=4, verbose_name='Title'),
        ),
    ]
