# Generated by Django 4.2.1 on 2023-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0006_rename_dept_id_department_dpet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='su_staff',
            name='author_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='AUTHOR NAME'),
        ),
    ]
