# Generated by Django 4.2.1 on 2023-06-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0008_alter_su_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='su_staff',
            name='name',
            field=models.CharField(max_length=256, verbose_name='STAFF NAME'),
        ),
    ]
