# Generated by Django 4.2.1 on 2023-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0009_alter_su_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='su_staff',
            name='title',
            field=models.CharField(choices=[('', ''), ('Prof.', 'Prof.'), ('Assoc. Prof', 'Assoc. Prof.'), ('Assoc. Prof. Dr', 'Assoc. Prof. Dr.'), ('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms')], default='', max_length=20, verbose_name='Title'),
        ),
    ]
