# Generated by Django 4.2.1 on 2023-07-10 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('su_staffs', '0009_alter_su_staff_name'),
    ]

    operations = [

    ]
