# Generated by Django 4.2.1 on 2023-07-11 12:47
from django.contrib.auth import get_user_model
from django.db import migrations, models


def link_user_account(apps, schema_editor):
    User = get_user_model()
    SU_Staff = apps.get_model('su_staffs', 'SU_Staff')
    users = User.objects.all()

    for user in users:

        try:
            staff_model = SU_Staff.objects.get(pk = user.get_username())
            staff_model.user = user
            staff_model.save()

        except SU_Staff.DoesNotExist:
            return

class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0014_auto_20230711_2047'),
    ]

    operations = [
        migrations.RunPython(link_user_account),
    ]
