# Generated by Django 4.2.1 on 2023-07-11 12:56


from django.contrib.auth import get_user_model
from django.db import migrations, models


def link_user_account(apps, schema_editor):
    User = get_user_model()
    SU_Staff = apps.get_model('su_staffs', 'SU_Staff')
    users = User.objects.all()

    for user in users:
        username = user.get_username()
        try:
            staff_model = SU_Staff.objects.get(staff_id=username)
            staff_model.user = user
            staff_model.save()
            print(f"Successfully linked User '{user}' with SU_Staff '{staff_model}'")
        except User.DoesNotExist:
            print(f"User '{user}' does not exist")
        except SU_Staff.DoesNotExist:
            print(f"SU_Staff with staff_id '{username}' does not exist")
        except Exception as e:
            print(f"An error occurred: {e}")
class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0015_auto_20230711_2052'),
    ]

    operations = [
    ]
