# Generated by Django 4.2.1 on 2023-07-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0017_auto_20230711_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='su_staff',
            name='user',
        ),
    ]
