# Generated by Django 4.2.1 on 2023-07-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0019_su_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='su_staff',
            name='user',
        ),
    ]
