# Generated by Django 4.2.1 on 2023-07-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff_id',
        ),
    ]
