# Generated by Django 4.2.1 on 2023-07-11 13:20

from django.contrib.auth import get_user_model
from django.db import migrations

def unlink_user_account(apps, schema_editor):
    User = get_user_model()
    users = User.objects.all()

    for user in users:
        if (user.get_username == 'root'):
            return
        else:
            try:
                user.delete()
                print(f"Successfully Deleted User '{user}'")
            except User.DoesNotExist:
                print(f"User '{user}' does not exist")
            except Exception as e:
                print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_staff_id'),
    ]

    operations = [
        migrations.RunPython(unlink_user_account),
    ]
