# Generated by Django 4.2.1 on 2023-07-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230711_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='scopus_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
