# Generated by Django 4.2.1 on 2023-06-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='SPONSOR ID')),
                ('sponsor_name', models.CharField(max_length=256, verbose_name='SPONSOR NAME')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('project_code', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='PROJECT CODE')),
                ('project_title', models.CharField(max_length=256, verbose_name='PROJECT TITLE')),
                ('grant_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='GRANT NAME')),
                ('sponsor', models.ForeignKey(blank=True, db_column='sponsor_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.sponsor')),
            ],
        ),
    ]
