# Generated by Django 4.2.1 on 2023-06-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0009_alter_su_staff_name'),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='su_staff',
            field=models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='su_staffs.su_staff'),
        ),
    ]
