# Generated by Django 4.2.1 on 2023-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0009_alter_su_staff_name'),
        ('grants', '0002_grant_su_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='su_staff', to='su_staffs.su_staff'),
        ),
        migrations.AddField(
            model_name='grant',
            name='project_end_date',
            field=models.DateField(blank=True, max_length=256, null=True, verbose_name='PROJECT END DATE'),
        ),
        migrations.AddField(
            model_name='grant',
            name='project_start_date',
            field=models.DateField(blank=True, max_length=256, null=True, verbose_name='PROJECT START DATE'),
        ),
    ]
