# Generated by Django 4.2.1 on 2023-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_grant_collaborators_grant_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_category',
            field=models.CharField(choices=[('International', 'International'), ('National', 'National'), ('Collaboration', 'Collaboration'), ('Private', 'Private')], default='National', max_length=20, verbose_name='SPONSOR CATEGORY'),
        ),
    ]
