# Generated by Django 4.2.1 on 2023-06-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_sponsor_sponsor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='amount_awarded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AMOUNT AWARDED'),
        ),
    ]
