# Generated by Django 4.2.1 on 2023-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0021_su_staff_user'),
        ('grants', '0006_alter_grant_amount_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='grant_su_staff', to='su_staffs.su_staff'),
        ),
    ]
