# Generated by Django 4.2.1 on 2023-06-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='PUBLISHER ID')),
                ('publisher_name', models.CharField(max_length=256, verbose_name='PUBLISHER NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('eid', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='EID')),
                ('doi', models.CharField(max_length=256, verbose_name='DOI')),
                ('publisher_name', models.ForeignKey(blank=True, db_column='publisher_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publisher')),
            ],
        ),
    ]
