# Generated by Django 4.2.1 on 2023-07-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('su_staffs', '0009_alter_su_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='PUBLISHER ID')),
                ('publisher_name', models.CharField(max_length=256, verbose_name='PUBLISHER NAME')),
            ],
        ),
        migrations.CreateModel(
            name='ScopusPublication',
            fields=[
                ('eid', models.CharField(default='-', primary_key=True, serialize=False, verbose_name='EID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='WOSPublication',
            fields=[
                ('wos_id', models.CharField(default='-', primary_key=True, serialize=False, verbose_name='UT (Unique WOS ID)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_source', models.CharField(choices=[('', ''), ('SCOPUS', 'SCOPUS'), ('WOS', 'WOS'), ('SCOPUS & WOS', 'SCOPUS & WOS')], default='', max_length=50, verbose_name='PUBLICATION SOUCE')),
                ('doi', models.CharField(blank=True, max_length=256, null=True, verbose_name='DOI')),
                ('doc_types', models.CharField(choices=[('', ''), ('Article', 'Article'), ('Review', 'Review'), ('Erratum', 'Erratum'), ('Note', 'Note'), ('Conference Paper', 'Conference Paper'), ('Editorial', 'Editorial'), ('Book Chapter', 'Book Chapter'), ('Book', 'Book'), ('Letter', 'Letter'), ('Data Paper', 'Data Paper'), ('Short Survey', 'Short Survey'), ('Proceedings Paper', 'Proceedings Paper'), ('Retraction', 'Retraction'), ('Meeting Abstract', 'Meeting Abstract'), ('Early Access', 'Early Access'), ('Book Review', 'Book Review'), ('Correction', 'Correction'), ('Biographical-Item', 'Biographical-Item'), ('Article; Early Access', 'Article; Early Access'), ('Article; Book Chapter', 'Article; Book Chapter'), ('Article; Data Paper', 'Article; Data Paper'), ('Letter; Early Access', 'Letter; Early Access')], default='', max_length=256, verbose_name='DOCUMENT TYPE')),
                ('title', models.CharField(default='-', verbose_name='Title')),
                ('source_title', models.CharField(default='-', max_length=256, verbose_name='Source Title')),
                ('authors', models.CharField(default='-', verbose_name='Authors')),
                ('published_year', models.DateField(blank=True, null=True, verbose_name='Published Year')),
                ('volume', models.CharField(blank=True, max_length=256, null=True, verbose_name='Volume')),
                ('issue', models.CharField(blank=True, max_length=256, null=True, verbose_name='Issue')),
                ('page_start', models.CharField(blank=True, max_length=256, null=True, verbose_name='Page Start')),
                ('page_end', models.CharField(blank=True, max_length=256, null=True, verbose_name='Page End')),
                ('industry', models.BooleanField(default=False, verbose_name='Industry')),
                ('international', models.BooleanField(default=False, verbose_name='International')),
                ('national', models.BooleanField(default=False, verbose_name='National')),
                ('editors', models.CharField(blank=True, max_length=256, null=True, verbose_name='Editors')),
                ('issn', models.CharField(blank=True, max_length=256, null=True, verbose_name='ISSN')),
                ('isbn', models.CharField(blank=True, max_length=256, null=True, verbose_name='ISBN')),
                ('publisher_name', models.ForeignKey(blank=True, db_column='publisher_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.publisher')),
                ('scopus_publication', models.ForeignKey(blank=True, db_column='eid', null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.scopuspublication')),
                ('su_staff', models.ManyToManyField(blank=True, default=None, null=True, related_name='publication_su_staff', to='su_staffs.su_staff')),
                ('wos_publication', models.ForeignKey(blank=True, db_column='wos_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.wospublication')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
