# Generated by Django 4.2.1 on 2023-07-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0009_alter_su_staff_name'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='su_staff',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='publications', to='su_staffs.su_staff'),
        ),
    ]
