# Generated by Django 4.2.1 on 2023-07-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_su_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_source',
            field=models.CharField(choices=[('-', '-'), ('SCOPUS', 'SCOPUS'), ('WOS', 'WOS'), ('SCOPUS & WOS', 'SCOPUS & WOS')], default='-', max_length=50, verbose_name='PUBLICATION SOUCE'),
        ),
    ]
