# Generated by Django 4.2.1 on 2023-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doc_types',
            field=models.CharField(choices=[('', ''), ('Article', 'Article'), ('Review', 'Review'), ('Erratum', 'Erratum'), ('Note', 'Note'), ('Conference Paper', 'Conference Paper'), ('Editorial', 'Editorial'), ('Book Chapter', 'Book Chapter'), ('Book', 'Book'), ('Letter', 'Letter'), ('Data Paper', 'Data Paper'), ('Short Survey', 'Short Survey'), ('Proceedings Paper', 'Proceedings Paper'), ('Retraction', 'Retraction'), ('Meeting Abstract', 'Meeting Abstract')], default='', max_length=256, verbose_name='DOCUMENT TYPE'),
        ),
    ]
