# Generated by Django 4.2.1 on 2023-06-30 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_doc_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doc_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('', ''), ('Article', 'Article'), ('Review', 'Review'), ('Erratum', 'Erratum'), ('Note', 'Note'), ('Conference Paper', 'Conference Paper'), ('Editorial', 'Editorial'), ('Book Chapter', 'Book Chapter'), ('Book', 'Book'), ('Letter', 'Letter'), ('Data Paper', 'Data Paper'), ('Short Survey', 'Short Survey'), ('Proceedings Paper', 'Proceedings Paper'), ('Retraction', 'Retraction'), ('Meeting Abstract', 'Meeting Abstract')], default='', max_length=50), blank=True, size=None),
        ),
    ]
