# Generated by Django 4.2.1 on 2023-06-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_doc_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doc_types',
            field=models.CharField(choices=[('', ''), ('Article', 'Article'), ('Review', 'Review'), ('Erratum', 'Erratum'), ('Note', 'Note'), ('Conference Paper', 'Conference Paper'), ('Editorial', 'Editorial'), ('Book Chapter', 'Book Chapter'), ('Book', 'Book'), ('Letter', 'Letter'), ('Data Paper', 'Data Paper'), ('Short Survey', 'Short Survey'), ('Proceedings Paper', 'Proceedings Paper'), ('Retraction', 'Retraction'), ('Meeting Abstract', 'Meeting Abstract'), ('Early Access', 'Early Access'), ('Book Review', 'Book Review'), ('Correction', 'Correction'), ('Biographical-Item', 'Biographical-Item'), ('Article; Early Access', 'Article; Early Access'), ('Article; Book Chapter', 'Article; Book Chapter'), ('Article; Data Paper', 'Article; Data Paper'), ('Letter; Early Access', 'Letter; Early Access')], default='', max_length=256, verbose_name='DOCUMENT TYPE'),
        ),
    ]
