# Generated by Django 4.2.1 on 2023-07-02 14:49

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_publication_doc_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(default='-', max_length=256, verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='publication',
            name='editors',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Editors'),
        ),
        migrations.AddField(
            model_name='publication',
            name='isnn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='publication',
            name='issn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ISSN'),
        ),
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Issue'),
        ),
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(default='-', max_length=256, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='publication',
            name='page_end',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Page End'),
        ),
        migrations.AddField(
            model_name='publication',
            name='page_start',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Page Start'),
        ),
        migrations.AddField(
            model_name='publication',
            name='published_year',
            field=models.IntegerField(default=publications.models.current_year, verbose_name='Published Year'),
        ),
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.CharField(default='Scopus', max_length=10, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='publication',
            name='source_title',
            field=models.CharField(default='-', max_length=256, verbose_name='Source Title'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(default='-', max_length=256, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Volume'),
        ),
    ]
