# Generated by Django 4.2.1 on 2023-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_authors_publication_editors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default='-', max_length=512, verbose_name='Title'),
        ),
    ]
