# Generated by Django 4.2.1 on 2023-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_publication_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(default='-', verbose_name='Link'),
        ),
    ]
