# Generated by Django 4.2.1 on 2023-07-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_rename_publication_scopuspublication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScopusPublication',
            new_name='Publication',
        ),
    ]
