# Generated by Django 4.2.1 on 2023-07-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_rename_scopuspublication_publication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='ScopusPublication',
        ),
    ]
