# Generated by Django 4.2.1 on 2023-07-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_rename_publication_scopuspublication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopuspublication',
            options={'verbose_name': 'Scopus Publication', 'verbose_name_plural': 'Scopus Publications'},
        ),
    ]
