# Generated by Django 4.2.1 on 2023-07-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_staffs', '0009_alter_su_staff_name'),
        ('publications', '0014_alter_scopuspublication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopuspublication',
            name='su_staff',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='scopus_su_staff', to='su_staffs.su_staff'),
        ),
    ]
