# Generated by Django 4.2.1 on 2023-07-05 14:05

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_rename_isnn_scopuspublication_isbn_wospublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wospublication',
            name='published_year',
            field=models.IntegerField(blank=True, default=publications.models.current_year, null=True, verbose_name='Published Year'),
        ),
    ]
