# Generated by Django 4.2.1 on 2023-07-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_alter_wospublication_published_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_source', models.CharField(choices=[('SCOPUS', 'SCOPUS'), ('WOS', 'WOS'), ('SCOPUS & WOS', 'SCOPUS & WOS')], default='-', max_length=20, verbose_name='PUBLICATION SOUCE')),
                ('scopus_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.scopuspublication')),
                ('wos_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.wospublication')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
